plugins {
    id 'maven-publish'
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}" apply false
    id 'net.neoforged.moddev' version '1.0.21' apply false
    id 'org.jetbrains.kotlin.jvm' version "${kotlin_version}" apply false
}

allprojects {
    apply plugin: 'maven-publish'

    version = project.mod_version
    group = project.maven_group

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://api.modrinth.com/maven" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://maven.terraformersmc.com/" }
        maven { url "https://maven.ladysnake.org/releases" } // Pour Cardinal Components
        maven { url "https://maven.blamejared.com" }          // JEI
        maven { url "https://maven.wispforest.io/releases" }  // Accessories
        maven { url "https://maven.su5ed.dev/releases" }      // Forgified Fabric API (Sinytra)
        maven { url "https://thedarkcolour.github.io/KotlinForForge/" } // Kotlin for Forge/NeoForge
    }
}

subprojects {
    plugins.withType(JavaPlugin) {
        tasks.withType(JavaCompile).configureEach {
            it.options.release = 21
        }

        java {
            withSourcesJar()
            sourceCompatibility = JavaVersion.VERSION_21
            targetCompatibility = JavaVersion.VERSION_21
        }
    }
}